name: brddge
description: dynamic platform designed to revolutionize professional networking by fostering authentic connections and unlocking meaningful opportunities
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  authentication_repository:
    path: packages/authentication_repository
  authenticator:
    path: packages/authenticator
  bloc: ^9.0.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  go_router: ^14.8.1
  intl: ^0.19.0
  supabase_flutter: ^2.8.4


dev_dependencies:

  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0


flutter:
  uses-material-design: true
  generate: true
