name: brddge
description: dynamic platform designed to revolutionize professional networking
  by fostering authentic connections and unlocking meaningful opportunities
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  app_preference_repository:
    path: packages/app_preference_repository
  authentication_repository:
    path: packages/authentication_repository
  authenticator:
    path: packages/authenticator
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.1.0
  font_awesome_flutter: ^10.8.0
  go_router: ^14.8.1
  hydrated_bloc: ^10.0.0
  intl: ^0.19.0
  shared_preferences: ^2.5.2
  supabase_flutter: ^2.8.4

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Gilory
      fonts:
        - asset: assets/fonts/gilory.ttf
