name: app_preference_repository
description: Implements the app preference interface
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  app_preferences_interface:
    path: ../app_preferences_interface
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
